export const Twitter = 'https://twitter.com/pingpongbuild'
export const Discord = 'https://discord.gg/3vYGdfDqvs'
export const HelpCenter = 'https://discord.gg/4YpR7TXN7F'
export const WhitePaper = '/PingPongWhitepaperV0.1.2.pdf'
export const Medium = 'https://medium.com/@pingpongbuild'